### ISSUE TITLE
NFS Config: Missing Newline Causes Errors

### ISSUE THREAD

**Issue by Heavybullets8** [smbonn2005/HomeOps#1294]
Hey,

I noticed an issue with Talos configurations for NFS where using `|-` instead of `|` removes the newline at the end of the file, causing errors.

#### Problem:
Using `|-`:
```yaml
        - content: |-
            [ NFSMount_Global_Options ]
            hard=True
            noatime=True
            nodiratime=True
            nconnect=8
```
leads to errors because the last line is ignored.

#### Affected Files Within:
```
kubernetes/main/bootstrap/talos
```

#### Solution:
Use `|` to keep the newline:
```yaml
        - content: |
            [ NFSMount_Global_Options ]
            hard=True
            noatime=True
            nodiratime=True
            nconnect=8
```

Then perform a `talosctl apply-config --mode reboot`

#### Additional Info:
Check for errors with:
```sh
talosctl logs syslogd | grep -i nfs
```
If you see something like:
```json
{"content":"conf_parse: last line non-terminated, ignored.","facility":3,"hostname":"localhost","priority":28,"severity":4,"tag":"mount.nfs","timestamp":"2024-07-23T21:17:18Z"}
```
it means the last line is ignored.

Verify with:
```sh
talosctl read /proc/mounts | grep nfs
```
If `nconnect` isn't listed, this is likely the issue.

#### Note:

It's a good idea to change ANY files listed in the Talos config to keep the newline, as this is likely not just an NFS issue.

Just a heads up to fix this in your configs.

**Comment by smbonn2005** [comment]
Good shout! Thanks for the Issue
